import type { Preset, PresetId } from "@morrow/contracts";

/**
 * Real preset definitions. Each preset is a routing policy: an ordered list of
 * preferred providers, per-provider model preferences, and concrete execution
 * budgets. Presets are not decorative — the router consumes them to choose a
 * configured provider+model and reports the decision.
 */
export const PRESETS: Preset[] = [
  {
    version: 1,
    id: "best-quality",
    label: "Best Quality",
    description: "Highest-capability frontier models, quality over speed and cost.",
    providerOrder: ["anthropic", "openai", "gemini", "openrouter", "deepseek", "openai-compatible", "ollama"],
    modelPreferences: {
      anthropic: ["claude-fable-5", "claude-opus-4-8"],
      openai: ["gpt-5.6-sol"],
      gemini: ["gemini-3.5-flash", "gemini-3.1-pro-preview"],
      openrouter: ["deepseek/deepseek-v4-pro"],
      deepseek: ["deepseek-v4-pro"],
      ollama: ["llama3.1"],
    },
    temperature: 0.3,
    reasoningEffort: "high",
    toolProfile: "read-only",
    contextBudgetBytes: 524288,
    outputBudgetTokens: 4096,
    timeoutMs: 120000,
    maxAttempts: 2,
    maxToolIterations: 8,
    privacy: "cloud",
    privacyDescription: "Sends your prompt and selected file contents to a hosted frontier provider.",
    costDescription: "Higher cost: prefers premium models.",
    requiresLocal: false,
  },
  {
    version: 1,
    id: "balanced",
    label: "Balanced",
    description: "A sensible default trading quality, speed, and cost.",
    providerOrder: ["openai", "anthropic", "gemini", "openrouter", "deepseek", "openai-compatible", "ollama"],
    modelPreferences: {
      openai: ["gpt-5.6-terra", "gpt-5.6-luna"],
      anthropic: ["claude-sonnet-5"],
      gemini: ["gemini-2.5-flash"],
      openrouter: ["openrouter/auto", "deepseek/deepseek-v4-flash"],
      deepseek: ["deepseek-v4-flash"],
      ollama: ["llama3.1"],
    },
    temperature: 0.4,
    reasoningEffort: "medium",
    toolProfile: "read-only",
    contextBudgetBytes: 524288,
    outputBudgetTokens: 4096,
    timeoutMs: 90000,
    maxAttempts: 2,
    maxToolIterations: 6,
    privacy: "cloud",
    privacyDescription: "Sends your prompt and selected file contents to a hosted provider.",
    costDescription: "Moderate cost: prefers efficient models.",
    requiresLocal: false,
  },
  {
    version: 1,
    id: "fast",
    label: "Fast",
    description: "Lowest-latency models for quick answers.",
    providerOrder: ["openai", "gemini", "deepseek", "openrouter", "anthropic", "openai-compatible", "ollama"],
    modelPreferences: {
      openai: ["gpt-5.6-luna"],
      gemini: ["gemini-2.5-flash-lite", "gemini-2.5-flash"],
      deepseek: ["deepseek-v4-flash"],
      openrouter: ["deepseek/deepseek-v4-flash"],
      anthropic: ["claude-haiku-4-5-20251001"],
      ollama: ["mistral"],
    },
    temperature: 0.5,
    reasoningEffort: "low",
    toolProfile: "read-only",
    contextBudgetBytes: 262144,
    outputBudgetTokens: 2048,
    timeoutMs: 60000,
    maxAttempts: 1,
    maxToolIterations: 4,
    privacy: "cloud",
    privacyDescription: "Sends your prompt and selected file contents to a hosted provider.",
    costDescription: "Low cost: prefers small fast models.",
    requiresLocal: false,
  },
  {
    version: 1,
    id: "cheap",
    label: "Cheap",
    description: "Minimizes cost using the least expensive hosted models.",
    providerOrder: ["deepseek", "gemini", "openai", "openrouter", "openai-compatible", "ollama", "anthropic"],
    modelPreferences: {
      deepseek: ["deepseek-v4-flash"],
      gemini: ["gemini-2.5-flash-lite"],
      openai: ["gpt-5.6-luna"],
      openrouter: ["deepseek/deepseek-v4-flash"],
      ollama: ["llama3.1"],
      anthropic: ["claude-haiku-4-5-20251001"],
    },
    temperature: 0.4,
    reasoningEffort: "low",
    toolProfile: "read-only",
    contextBudgetBytes: 262144,
    outputBudgetTokens: 2048,
    timeoutMs: 90000,
    maxAttempts: 1,
    maxToolIterations: 4,
    privacy: "cloud",
    privacyDescription: "Sends your prompt and selected file contents to a low-cost hosted provider.",
    costDescription: "Lowest hosted cost.",
    requiresLocal: false,
  },
  {
    version: 1,
    id: "coding",
    label: "Coding",
    description: "Tuned for code understanding: strong models, low temperature, more tool turns.",
    providerOrder: ["anthropic", "openai", "deepseek", "openrouter", "gemini", "openai-compatible", "ollama"],
    modelPreferences: {
      anthropic: ["claude-opus-4-8", "claude-sonnet-5"],
      openai: ["gpt-5.6-sol"],
      deepseek: ["deepseek-v4-pro"],
      openrouter: ["deepseek/deepseek-v4-pro"],
      gemini: ["gemini-3.5-flash", "gemini-3.1-pro-preview"],
      ollama: ["qwen2.5"],
    },
    temperature: 0.2,
    reasoningEffort: "high",
    toolProfile: "read-only",
    contextBudgetBytes: 786432,
    outputBudgetTokens: 4096,
    timeoutMs: 120000,
    maxAttempts: 2,
    maxToolIterations: 10,
    privacy: "cloud",
    privacyDescription: "Sends your prompt and selected file contents to a hosted provider.",
    costDescription: "Moderate to higher cost: prefers strong coding models.",
    requiresLocal: false,
  },
  {
    version: 1,
    id: "research",
    label: "Research",
    description: "Large-context models for synthesis across many files.",
    providerOrder: ["gemini", "anthropic", "openai", "openrouter", "deepseek", "openai-compatible", "ollama"],
    modelPreferences: {
      gemini: ["gemini-3.5-flash", "gemini-3.1-pro-preview"],
      anthropic: ["claude-sonnet-5", "claude-opus-4-8"],
      openai: ["gpt-5.6-terra"],
      openrouter: ["openrouter/auto", "deepseek/deepseek-v4-pro"],
      deepseek: ["deepseek-v4-pro"],
      ollama: ["llama3.1"],
    },
    temperature: 0.5,
    reasoningEffort: "medium",
    toolProfile: "read-only",
    contextBudgetBytes: 786432,
    outputBudgetTokens: 4096,
    timeoutMs: 150000,
    maxAttempts: 2,
    maxToolIterations: 10,
    privacy: "cloud",
    privacyDescription: "Sends your prompt and selected file contents to a hosted provider.",
    costDescription: "Variable cost: prefers large-context models.",
    requiresLocal: false,
  },
  {
    version: 1,
    id: "private-local",
    label: "Private Local",
    description: "Runs only on local providers. Nothing leaves your machine.",
    providerOrder: ["ollama"],
    modelPreferences: {
      ollama: ["llama3.1", "qwen2.5", "mistral", "phi3"],
    },
    temperature: 0.4,
    reasoningEffort: null,
    toolProfile: "read-only",
    contextBudgetBytes: 262144,
    outputBudgetTokens: 2048,
    timeoutMs: 120000,
    maxAttempts: 1,
    maxToolIterations: 6,
    privacy: "local-only",
    privacyDescription: "Inference runs locally via Ollama. No prompt or file content leaves the machine.",
    costDescription: "Free: uses your local hardware.",
    requiresLocal: true,
  },
];

const BY_ID = new Map<PresetId, Preset>(PRESETS.map((p) => [p.id, p]));

export function listPresets(): Preset[] {
  return PRESETS;
}

export function getPreset(id: PresetId): Preset | undefined {
  return BY_ID.get(id);
}

export function isPresetId(value: string): value is PresetId {
  return BY_ID.has(value as PresetId);
}

export const DEFAULT_PRESET_ID: PresetId = "balanced";
