import { z } from "zod";
export const SchemaVersionSchema=z.literal(1); export const TaskStatusSchema=z.enum(["queued","running","verified","failed","interrupted"]); export const PlanStepStatusSchema=z.enum(["pending","running","completed","failed","skipped"]);
export const ProjectSchema=z.object({version:SchemaVersionSchema,id:z.string(),name:z.string().min(1),workspacePath:z.string().min(1),createdAt:z.string().datetime()}).strict();
export const CreateProjectSchema=z.object({name:z.string().trim().min(1).max(120),workspacePath:z.string().min(1)});
export const PlanStepSchema=z.object({version:SchemaVersionSchema,id:z.string(),taskId:z.string(),position:z.number().int().positive(),title:z.string(),status:PlanStepStatusSchema}).strict();
export const TaskSchema=z.object({version:SchemaVersionSchema,id:z.string(),projectId:z.string(),kind:z.literal("inspect_workspace"),status:TaskStatusSchema,createdAt:z.string().datetime(),updatedAt:z.string().datetime()}).strict();
export const CreateTaskSchema=z.object({projectId:z.string().min(1),kind:z.literal("inspect_workspace")});
export const TaskEventSchema=z.object({id:z.string(),taskId:z.string(),sequence:z.number().int().positive(),type:z.enum(["task.created","task.running","plan.created","workspace.inspected","task.verified","task.failed","task.interrupted","task.recovery_required"]),createdAt:z.string(),payload:z.record(z.string(),z.unknown())});
export const TaskEvidenceSchema=z.object({id:z.string(),taskId:z.string(),kind:z.literal("file"),relativePath:z.string(),createdAt:z.string()});
export const ExecutionDisclosureSchema=z.object({taskId:z.string(),mode:z.literal("deterministic-local"),networkAccess:z.literal("disabled"),workspacePath:z.string(),estimatedCost:z.literal("$0.00")});
export const VerificationResultSchema=z.object({taskId:z.string(),status:z.literal("verified"),summary:z.string(),truncated:z.boolean()});
export const StructuredApiErrorSchema=z.object({version:SchemaVersionSchema,error:z.object({code:z.string(),message:z.string()}).strict()}).strict();
export type Project=z.infer<typeof ProjectSchema>; export type Task=z.infer<typeof TaskSchema>; export type TaskEvent=z.infer<typeof TaskEventSchema>;
export type TaskStatus=z.infer<typeof TaskStatusSchema>; export type PlanStepStatus=z.infer<typeof PlanStepStatusSchema>; export type StructuredApiError=z.infer<typeof StructuredApiErrorSchema>;
